name: .NET

on:
  push:
    branches: [ "master" ]
    paths:
      - 'movie-recognizer/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'movie-recognizer/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Setup Aspire
      run: |
        dotnet workload update
        dotnet workload install aspire
    - name: Restore dependencies
      working-directory: movie-recognizer
      run: dotnet restore
    - name: Build
      working-directory: movie-recognizer
      run: dotnet build --no-restore
#    - name: Set secrets
#      run: |
#        cd src/Services/Movies/Movies.API
#        dotnet user-secrets set "OMDb:ApiKey" "${{ secrets.OMDB_API_KEY }}"
    - name: Test
      working-directory: movie-recognizer
      run: dotnet test --no-build --verbosity normal