name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Setup Aspire
      run: |
        dotnet workload update
        dotnet workload install aspire
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Set secrets
      run: |
        cd src/Services/Movies/Movies.API
        dotnet user-secrets set "OMDb:ApiKey" "${{ secrets.OMDB_API_KEY }}"
    - name: Test
      run: dotnet test --no-build --verbosity normal

  render_docs:
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      - uses: severgroup-tt/actions-drawio-cli@v0.0.2
        with:
          source: docs/MovieRecognizer.drawio
          destination: docs/MovieRecognizer.png
          format: png
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: docs/*.png
          commit_message: Update diagrams