name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  render_docs:
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      - uses: severgroup-tt/actions-drawio-cli@v0.0.2
        with:
          source: docs/MovieRecognizer.drawio
          destination: docs/MovieRecognizer.png
          format: png
      - uses: severgroup-tt/actions-drawio-cli@v0.0.2
        with:
          source: docs/Architecture.drawio
          destination: docs/Architecture.png
          format: png
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: docs/*
          commit_message: Render docs
