name: Terraform plan

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3

    - run: |
        curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | \
        bash -s -- -i /opt/yc -n
        echo "/opt/yc/bin" >> $GITHUB_PATH

    - run: yc config profile create terraform

    - run: echo "$YC_SA_JSON_CREDENTIALS" > key.json
      env:
        YC_SA_JSON_CREDENTIALS: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

    - run: |
        yc config set service-account-key key.json
        yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
        yc config set folder-id ${{ secrets.YC_FOLDER_ID }}

    - run: |
        export YC_TOKEN=$(yc iam create-token)
        export YC_CLOUD_ID=$(yc config get cloud-id)
        export YC_FOLDER_ID=$(yc config get folder-id)

    - name: terraform plan
      uses: dflook/terraform-plan@v1
      with:
        path: terraform
        backend_config: |
          access_key=${{ secrets.YC_SA_ACCESS_KEY }}
          secret_key=${{ secrets.YC_SA_SECRET_KEY }}