name: Terraform apply

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  apply:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3

    - name: Install YC CLI
      run: |
        curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | \
        bash -s -- -i /opt/yc -n
        echo "/opt/yc/bin" >> $GITHUB_PATH

    - name: Configure YC CLI
      run: |
        yc config profile create default
        echo "$YC_SA_JSON_CREDENTIALS" > key.json
        yc config set service-account-key key.json
        yc config set cloud-id "$YC_CLOUD_ID"
        yc config set folder-id "$YC_FOLDER_ID"
      env:
        YC_SA_JSON_CREDENTIALS: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
        YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}

    - name: Set YC environment variables
      run: |
        echo "YC_TOKEN=$(yc iam create-token)" >> $GITHUB_ENV
        echo "YC_CLOUD_ID=$(yc config get cloud-id)" >> $GITHUB_ENV
        echo "YC_FOLDER_ID=$(yc config get folder-id)" >> $GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Publish ReceiveVideoHandler
      run: |
        dotnet publish recognition-functions/ReceiveVideoHandler/ReceiveVideoHandler.csproj -o receive-video-handler

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Api/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/movie-recognizer-api:${{ github.sha }}

    - name: Terraform apply
      uses: dflook/terraform-apply@v1
      with:
        auto_approve: true
        path: terraform
        backend_config: |
          access_key=${{ secrets.YC_SA_ACCESS_KEY }}
          secret_key=${{ secrets.YC_SA_SECRET_KEY }}
        variables: |
          deployer_access_key = "${{ secrets.YC_SA_ACCESS_KEY }}"
          deployer_secret_key = "${{ secrets.YC_SA_SECRET_KEY }}"
          folder_id = "${{ secrets.YC_FOLDER_ID }}"
          docker_username = "${{ secrets.DOCKERHUB_USERNAME }}"
          docker_api_repository = "movie-recognizer-api"
          github_sha = "${{ github.sha }}"